### ISSUE TITLE
how to use it 

### ISSUE THREAD

**Issue by Zebjia** [marpontes/tapa#10]
i download tapa and  restart pentaho Bi   but i can't find tapa on the menu  and  SPARKL display let me restart again ，so  i restart  many times...it  desn't work... please help

**Comment by marpontes** [comment]
Hi, when tapa is installed, it only delivers a _Perspective_.

When I say _Perspective_, I mean that same menu where you access _Pentaho Marketplace_, _Files Browser_ and so on.

If you won't find it there, then you have a problem.

You can alternatively try to access the address `http://localhost:8080/pentaho/content/tapa/admin-ui/index.html` - replace localhost:8080 for your url, if different.

**Comment by Zebjia** [comment]
thank you   i slove the problem  tapa is so good
