### ISSUE TITLE
Replaced application name, port, and hostname

### ISSUE THREAD

**Issue by gaussium** [marpontes/tapa#11]
I have basically replaced the pentaho application name, port, and hostname. e.g http://192.168.1.55:7070/blah/Login. It's seems working fine i've already install some plugins and the only plugin that hasn't work is tapa. I got a blank white screen after manual installation i guess there is an issue in PUCLogin.jsp. Any advise

**Comment by marpontes** [comment]
Hi, @gaussium,

The [server-side code](https://github.com/marpontes/tapa-template-engine) has no app-name dependency, so on blind I think it might be some client-side code.

If you're saying it's a blank page, it then doesn't look to [this](https://github.com/marpontes/tapa/blob/master/install/jsp/PUCLogin.jsp#L236) (when rendered), right?

The default Pentaho template that comes enabled after you install Tapa, has a [strong dependency](https://github.com/marpontes/tapa/blob/master/resources/templates/pentaho/index.html#L18) on the webapp name. Unfortunately I consider this a minor issue and it should be included into your app-name-change-checklist and change this content manually on your installation. 

I guess that this should get you going.

On the admin part, there were some silly dependencies that I've just pulled to the trunk and will eventually include into a next release.

These last dependencies would beak the possibility to use the Tapa admin UI, though the core functionalities should work normally.

Anyways, I suggest you to try the master branch on Pentaho 6.x.

If you have any other problems, I'd like to know your JVM version/vendor, as well as pentaho version and a full catalina.out startup log.

Please let me know if you managed make it work.

**Comment by marpontes** [comment]
https://github.com/marpontes/tapa/commit/61d879742165e33baca47850e356479613000d3a

**Comment by marpontes** [comment]
Closing for the lack of feedback
